spring.application.name=transfer-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/transferdb}
spring.data.mongodb.auto-index-creation=true
server.port=${SERVER_PORT:8083}
management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [${spring.application.name}] [correlationId=%X{correlationId:-none}] %logger{36} - %msg%n
