spring.application.name=transfer-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/transferdb}
spring.data.mongodb.database=${MONGODB_DATABASE:transferdb}
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:${SERVER_PORT:8083}}
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [${spring.application.name}] [correlationId=%X{correlationId:-none}] %logger{36} - %msg%n
